"""
Demonstration de l'outil MCP get_stock_alerts - Simulation
"""
print("=" * 60)
print("  MCP Inspector - Outil: get_stock_alerts")
print("=" * 60)
print()
print("Requete:")
print("  {")
print('    "tool": "get_stock_alerts",')
print('    "arguments": {}')
print("  }")
print()
print("Reponse:")
print("-" * 40)
print("[!] ALERTE STOCK :")
print("- Ordinateur Portable HP : seulement 3 restants !")
print("- Smartphone Galaxy A54  : seulement 1 restants !")
print("-" * 40)
print()
print("[SUCCES] Outil execute avec succes (200 OK)")
print()
print("Note: Donnees brutes retournees par le serveur MCP.")
print("L'analyse et recommandations sont generees par Claude (LLM).")
